### ISSUE TITLE
Overridden ENVs getting filtered out incorrectly

### ISSUE THREAD

**Issue by goulinkh** [canonical-web-and-design/konf#26]
Some override envs are missing, here is an example that illustrates the problem:

```yaml
# Override demo
demo:
  env:
    - name: WORKPLACE_ENGINEERING_DATABASE_URL
      secretKeyRef:
        key: workplace_engineering_database_url
        name: hiring-com
```

This is getting filtered out because it container the keyword `DATABASE_URL` in the name.
